### ISSUE TITLE
Kode for sykehus-hierarki

### ISSUE THREAD

**Issue by arnfinn** [SKDE-Felles/qmongr#22]
I data fra registre får vi org.-nummer. Vi trenger funksjon som mapper denne koden til sykehus, HF og RHF.

For Helse Nord blir det noe ala dette:

![sykehusstruktur](https://user-images.githubusercontent.com/136346/74235638-caa56680-4ccf-11ea-9c95-c4bb5e1986eb.png)

**Comment by arnfinn** [comment]
I analyse-seksjonen har vi egne koder for sykehus, HF og RHF, som vi har brukt i mange år. Et alternativ er å kode org.nummer over til sykehusnummer etc. slik vi gjør det her: https://github.com/SKDE-Analyse/sas_codes/blob/master/tilrettelegging/npr/behandler.sas

Fordelen er at vi allerede må gjøre denne mappingen mellom org.nummer og sykehus når vi får data fra NPR. Vi gjør derfor en ekstra kvalitetssikring når vi tilrettelegger data fra NPR og det blir ikke mye ekstraarbeid. I tillegg har analyseseksjonen erfaring med å bruke disse interne nummer.

Man burde kanskje lage en funksjon i SAS som leser inn alle org.nummer og legger på BehSh, BehHF og BehRHF ved å bruke denne makroen? Dette for å unngå at man har kode for denne mappingen flere steder (og på flere språk). Noe ala dette:

```sas
/* Read csv */
proc import datafile = '/folders/myfolders/orgnum.csv'
out = orgnum
dbms = csv ;
run;

/* Add behSh etc. */
%behandler(innDataSett=orgnum, utDataSett=orgnum_beh);

/* Save csv */
proc export data=orgnum_beh  
outfile='/folders/myfolders/orgnum_beh.csv'  
dbms=csv;
run;
```

**Comment by JaniceShu** [comment]
I downloaded the underenhetsliste from Brønnøysund and used the NPR tilrettelegging code to assign behandlendesykehus. 

In addition also looked at the org nummer that was not assigned a sykehus by the above mentioned syntex to see if there are any others to be included. I found about 15, most are privat.

**Comment by JaniceShu** [comment]
Attached is the list of organisajonsnummer we expect to get from register, which we can use to assign sykehusnavn.

[org_nr_qmongr.xlsx](https://github.com/SKDE-Felles/qmongr/files/4192535/org_nr_qmongr.xlsx)

**Comment by arnfinn** [comment]
Close with 895a756
