### ISSUE TITLE
Docker: install `qmongr` from `.` and not from github

### ISSUE THREAD

**Issue by arnfinn** [SKDE-Felles/qmongr#40]
Thus, install current version and not the external master version on github. Will be possible to run and check the docker locally.

Change this line:
https://github.com/SKDE-Felles/qmongr/blob/a8a28ef56fac29ebeff7df3703c70b772e658dbc/Dockerfile#L21

**Comment by arnfinn** [comment]
A way of also installing dependencies:
```
devtools::install_deps(".")
```

**Comment by areedv** [comment]
Probably fixed in #42
