### ISSUE TITLE
Travis: let lintr-bot comment when lintr issues

### ISSUE THREAD

**Issue by arnfinn** [SKDE-Felles/qmongr#58]
For now it is either @arnfinn or @areedv that is commenting on PR with lintr issues. Not sure how to make [lintr-bot](https://github.com/lintr-bot) do the commenting.

![Screenshot 2020-02-25 at 13 49 14](https://user-images.githubusercontent.com/136346/75249057-bb491180-57d5-11ea-9ab7-ce068f1f0d07.png)

**Comment by areedv** [comment]
Maybe this is due to the definition of _id_rsa_, _GITHUB_TOKEN_ or _GITHUB_PAT_ env vars at travis?

**Comment by arnfinn** [comment]
Probably because of `GITHUB_TOKEN`. From here:
https://github.com/jimhester/lintr/blob/01e57c2124891b965c02626b27559c95f3218679/R/zzz.R#L208

```
    comment_token = Sys.getenv("GITHUB_TOKEN", unset = NA) %||% rot(
      paste0(
        "0n12nn72507",
        "r6273qnnp34",
        "43qno7q42n1",
        "n71nn28")
      , 54 - 13),
```

I guess we can replace `GITHUB_TOKEN` with another name?
